include:
  # Левая половина (SuperMini)
  - board: nrf52840dongle_nrf52840
    shield: charybdis_left
    keymap: qwerty
  # Правая половина (SuperMini)
  - board: nrf52840dongle_nrf52840
    shield: charybdis_right
    keymap: qwerty
  # Утилита для сброса настроек (всегда полезно иметь)
  - board: nrf52840dongle_nrf52840
    shield: settings_reset
